/* SPDX-License-Identifier: LGPL-2.1-or-later */
#include "goodix_fpi_usb_backend.h"
#include "goodix_tls_server.h"
#include "goodix_usb_router.h"
#include <openssl/ssl.h>
#include <string.h>
/* g_assert_cmpmem in some GLib versions stores lengths in int, which trips
 * -Wsign-conversion under -Wconversion.  Use a size_t-safe local wrapper. */
#define ASSERT_CMPMEM(m1, l1, m2, l2) G_STMT_START { \
  gconstpointer __m1 = (m1), __m2 = (m2); \
  gsize __l1 = (l1), __l2 = (l2); \
  g_assert_cmpuint (__l1, ==, __l2); \
  if (__l1 != 0) \
    g_assert_true (memcmp (__m1, __m2, __l1) == 0); \
} G_STMT_END
static const guint8 psk[]={0x44,0x32,0x37,0x36,0x2d,0x53,0x59,0x4e,0x54,0x48,0x45,0x54,0x49,0x43,0x21,0x21};
typedef struct { GByteArray *server_wire,*plain; GoodixTlsServer *server; GoodixTlsAudit audit; GoodixUsbRouter *router; GoodixFpiUsbBackend *backend; guint64 generation; guint a0,b0,in_submits,out_submits; gboolean expect_tls_failure; } Fixture;
static void bytes_append(GByteArray*a,GBytes*b){gsize n;const guint8*p=g_bytes_get_data(b,&n);g_byte_array_append(a,p,(guint)n);}
static void tls_out(GBytes*b,gpointer d){Fixture*f=d;bytes_append(f->server_wire,b);if(f->backend){g_autoptr(GError)e=NULL;g_assert_true(goodix_fpi_usb_backend_submit_out(f->backend,f->generation,b,&e));g_assert_no_error(e);}}
static void plain_out(GBytes*b,gpointer d){bytes_append(((Fixture*)d)->plain,b);}
static void a0_cb(guint8 t,GBytes*b,gpointer d){(void)b;g_assert_cmpuint(t,==,0xa0);((Fixture*)d)->a0++;}
static void b0_cb(guint8 t,GBytes*b,gpointer d){Fixture*f=d;gsize n;const guint8*p=g_bytes_get_data(b,&n);g_autoptr(GError)e=NULL;g_assert_cmpuint(t,==,0xb0);f->b0++;g_assert_cmpuint(n,>,4);gboolean ok=goodix_tls_server_push(f->server,p+4,n-4,&e);if(f->expect_tls_failure){if(!ok)g_clear_error(&e);}else{g_assert_true(ok);g_assert_no_error(e);}}
static void seam(GoodixFpiUsbBackend*b,GoodixUsbDirection dir,guint64 gen,GBytes*bytes,gpointer d){Fixture*f=d;(void)b;g_assert_cmpuint(gen,==,f->generation);if(dir==GOODIX_USB_TRANSFER_IN){g_assert_null(bytes);f->in_submits++;}else{g_assert_nonnull(bytes);f->out_submits++;}}
static void fixture_init(Fixture*f){memset(f,0,sizeof*f);f->server_wire=g_byte_array_new();f->plain=g_byte_array_new();f->router=goodix_usb_router_new(a0_cb,b0_cb,f);f->generation=1;goodix_usb_router_begin_generation(f->router,f->generation);f->backend=goodix_fpi_usb_backend_new(NULL,f->router,0x81,0x01,4096);goodix_fpi_usb_backend_set_submit_seam(f->backend,seam,f);g_autoptr(GCancellable)c=g_cancellable_new();g_autoptr(GError)e=NULL;g_assert_true(goodix_fpi_usb_backend_begin_generation(f->backend,f->generation,c,&e));g_assert_no_error(e);f->server=goodix_tls_server_new(psk,sizeof psk,tls_out,plain_out,f,&f->audit,&e);g_assert_no_error(e);g_assert_nonnull(f->server);}
static void fixture_clear(Fixture*f){goodix_tls_server_free(f->server);goodix_fpi_usb_backend_free(f->backend);goodix_usb_router_free(f->router);g_byte_array_unref(f->server_wire);g_byte_array_unref(f->plain);}
static void feed_frame(Fixture*f,guint8 type,const guint8*p,gsize n,gboolean split,guint64 gen){g_autoptr(GByteArray)x=g_byte_array_new();guint8 h[4]={type,(guint8)n,(guint8)(n>>8),(guint8)(type+(guint8)n+(guint8)(n>>8))};g_autoptr(GError)e=NULL;guint b0_before=f->b0;g_byte_array_append(x,h,4);g_byte_array_append(x,p,(guint)n);g_assert_true(goodix_fpi_usb_backend_arm_receive(f->backend,f->generation,&e));if(split){goodix_fpi_usb_backend_complete_receive(f->backend,gen,x->data,2,NULL);if(gen==f->generation){g_assert_cmpuint(f->b0,==,b0_before);g_assert_true(goodix_fpi_usb_backend_arm_receive(f->backend,f->generation,&e));goodix_fpi_usb_backend_complete_receive(f->backend,gen,x->data+2,x->len-2,NULL);}}else goodix_fpi_usb_backend_complete_receive(f->backend,gen,x->data,x->len,NULL);}
typedef struct { SSL_CTX*ctx;SSL*ssl;gboolean bad_identity,bad_psk; } Client;
static unsigned int client_cb(SSL*s,const char*h,char*i,unsigned int im,unsigned char*out,unsigned int om){Client*c=SSL_get_app_data(s);(void)h;g_strlcpy(i,c->bad_identity?"Wrong_identity":"Client_identity",im);g_assert_cmpuint(om,>=,sizeof psk);memcpy(out,psk,sizeof psk);if(c->bad_psk)out[0]^=0xff;return sizeof psk;}
static void client_init(Client*c){c->ctx=SSL_CTX_new(TLS_client_method());g_assert_cmpint(SSL_CTX_set_min_proto_version(c->ctx,TLS1_2_VERSION),==,1);g_assert_cmpint(SSL_CTX_set_max_proto_version(c->ctx,TLS1_2_VERSION),==,1);g_assert_cmpint(SSL_CTX_set_cipher_list(c->ctx,"PSK-AES128-GCM-SHA256"),==,1);SSL_CTX_set_psk_client_callback(c->ctx,client_cb);c->ssl=SSL_new(c->ctx);SSL_set_app_data(c->ssl,c);BIO*in=BIO_new(BIO_s_mem());BIO*out=BIO_new(BIO_s_mem());BIO_set_mem_eof_return(in,-1);SSL_set_bio(c->ssl,in,out);SSL_set_connect_state(c->ssl);}
static void client_clear(Client*c){SSL_free(c->ssl);SSL_CTX_free(c->ctx);}
static gboolean pump(Fixture*f,Client*c,gboolean fragmented){for(guint k=0;k<64;k++){guint8 buf[4096];int r=SSL_do_handshake(c->ssl);if(r!=1){int e=SSL_get_error(c->ssl,r);if(e!=SSL_ERROR_WANT_READ&&e!=SSL_ERROR_WANT_WRITE)return FALSE;}int n;while((n=BIO_read(SSL_get_wbio(c->ssl),buf,sizeof buf))>0)feed_frame(f,0xb0,buf,(gsize)n,fragmented,f->generation);if(f->server_wire->len){BIO_write(SSL_get_rbio(c->ssl),f->server_wire->data,(int)f->server_wire->len);g_byte_array_set_size(f->server_wire,0);}if(SSL_is_init_finished(c->ssl)&&goodix_tls_server_get_state(f->server)==GOODIX_TLS_STATE_ESTABLISHED)return TRUE;if(goodix_tls_server_get_state(f->server)==GOODIX_TLS_STATE_TERMINAL)return FALSE;}return FALSE;}
static void test_handshake_application_router(void){Fixture f;Client c={0};fixture_init(&f);client_init(&c);g_assert_true(pump(&f,&c,TRUE));g_assert_cmpstr(goodix_tls_server_get_protocol(f.server),==,"TLSv1.2");g_assert_cmpstr(goodix_tls_server_get_cipher(f.server),==,"PSK-AES128-GCM-SHA256");g_assert_cmpuint(f.audit.handshake_count,==,1);g_assert_cmpuint(f.audit.secret_handoff_count,==,1);g_assert_true(f.audit.project_secret_zeroized);g_assert_false(goodix_tls_server_test_second_handoff(f.server));g_assert_true(f.audit.second_handoff_rejected);const char*m1="opaque-test-data",*m2="second-record";g_assert_cmpint(SSL_write(c.ssl,m1,(int)strlen(m1)),>,0);guint8 buf[4096];int n;while((n=BIO_read(SSL_get_wbio(c.ssl),buf,sizeof buf))>0)feed_frame(&f,0xb0,buf,(gsize)n,TRUE,f.generation);g_assert_cmpint(SSL_write(c.ssl,m2,(int)strlen(m2)),>,0);while((n=BIO_read(SSL_get_wbio(c.ssl),buf,sizeof buf))>0)feed_frame(&f,0xb0,buf,(gsize)n,FALSE,f.generation);g_autofree gchar*expect=g_strconcat(m1,m2,NULL);ASSERT_CMPMEM(f.plain->data,f.plain->len,expect,strlen(expect));g_assert_cmpuint(f.audit.plaintext_delivery_count,==,2);g_assert_cmpuint(f.out_submits,>,0);g_assert_cmpuint(goodix_fpi_usb_backend_get_real_submit_count(f.backend),==,0);goodix_tls_server_cancel(f.server);goodix_tls_server_cancel(f.server);g_assert_cmpuint(f.audit.terminal_completion_count,==,1);client_clear(&c);fixture_clear(&f);}
static void test_a0_stale_cancel_backend(void){Fixture f;fixture_init(&f);const guint8 a[]={1,2};feed_frame(&f,0xa0,a,sizeof a,FALSE,f.generation);g_assert_cmpuint(f.a0,==,1);g_assert_cmpuint(f.b0,==,0);g_autoptr(GError)e=NULL;g_assert_true(goodix_fpi_usb_backend_arm_receive(f.backend,f.generation,&e));g_assert_false(goodix_fpi_usb_backend_arm_receive(f.backend,f.generation,&e));g_clear_error(&e);goodix_fpi_usb_backend_complete_receive(f.backend,f.generation-1,a,sizeof a,NULL);g_assert_cmpuint(goodix_fpi_usb_backend_get_outstanding(f.backend),==,1);goodix_fpi_usb_backend_cancel(f.backend);goodix_tls_server_cancel(f.server);goodix_fpi_usb_backend_complete_receive(f.backend,f.generation,a,sizeof a,NULL);g_assert_true(goodix_fpi_usb_backend_is_drained(f.backend));g_assert_cmpuint(f.a0,==,1);g_autoptr(GBytes)b=g_bytes_new_static(a,sizeof a);g_assert_false(goodix_fpi_usb_backend_submit_out(f.backend,f.generation,b,&e));g_assert_nonnull(e);fixture_clear(&f);}
static void test_bad_credentials_and_terminal(void){for(guint mode=0;mode<2;mode++){Fixture f;Client c={0};fixture_init(&f);client_init(&c);f.expect_tls_failure=TRUE;c.bad_identity=mode==0;c.bad_psk=mode==1;g_assert_false(pump(&f,&c,FALSE));g_assert_cmpint(goodix_tls_server_get_state(f.server),==,GOODIX_TLS_STATE_TERMINAL);g_assert_cmpuint(f.audit.terminal_completion_count,==,1);guint8 x=0;g_autoptr(GError)e=NULL;g_assert_false(goodix_tls_server_push(f.server,&x,1,&e));client_clear(&c);fixture_clear(&f);}Fixture f;fixture_init(&f);guint8 truncated[]={0x16,3,3,0,4,1};g_autoptr(GError)e=NULL;g_assert_true(goodix_tls_server_push(f.server,truncated,sizeof truncated,&e));g_assert_false(goodix_tls_server_eof(f.server,&e));g_assert_cmpuint(f.audit.terminal_completion_count,==,1);fixture_clear(&f);}

static void async_noop(GoodixFpiUsbBackend*b,GoodixUsbDirection d,guint64 g,GBytes*x,gpointer u){(void)b;(void)d;(void)g;(void)x;(void)u;}
static void drained_count(GoodixFpiUsbBackend*b,gpointer u){(void)b;(*(guint*)u)++;}
static void test_async_in_cancel_drain(void){
  GoodixUsbRouter*r=goodix_usb_router_new(NULL,NULL,NULL);GoodixFpiUsbBackend*b=goodix_fpi_usb_backend_new(NULL,r,0x81,0x01,64);g_autoptr(GCancellable)c=g_cancellable_new();g_autoptr(GError)e=NULL;guint drained=0;const guint8 frame[]={0xa0,1,0,0xa1,1};
  goodix_fpi_usb_backend_set_async_submit_seam(b,async_noop,NULL);goodix_fpi_usb_backend_set_drained_callback(b,drained_count,&drained);goodix_usb_router_begin_generation(r,10);g_assert_true(goodix_fpi_usb_backend_begin_generation(b,10,c,&e));g_assert_true(goodix_fpi_usb_backend_arm_receive(b,10,&e));g_assert_cmpuint(goodix_fpi_usb_backend_get_outstanding(b),==,1);g_assert_false(goodix_fpi_usb_backend_can_free(b));goodix_fpi_usb_backend_cancel(b);g_assert_cmpuint(goodix_fpi_usb_backend_get_outstanding(b),==,1);g_assert_false(goodix_fpi_usb_backend_is_drained(b));g_assert_false(goodix_fpi_usb_backend_begin_generation(b,11,c,&e));g_clear_error(&e);g_autoptr(GError)cancelled=g_error_new_literal(G_IO_ERROR,G_IO_ERROR_CANCELLED,"synthetic cancellation");goodix_fpi_usb_backend_complete_receive(b,10,NULL,0,cancelled);g_assert_cmpuint(drained,==,1);g_assert_true(goodix_fpi_usb_backend_is_drained(b));g_assert_true(goodix_fpi_usb_backend_can_free(b));g_assert_true(goodix_fpi_usb_backend_begin_generation(b,11,c,&e));goodix_usb_router_begin_generation(r,11);g_assert_true(goodix_fpi_usb_backend_arm_receive(b,11,&e));goodix_fpi_usb_backend_complete_receive(b,10,frame,sizeof frame,NULL);g_assert_cmpuint(goodix_fpi_usb_backend_get_outstanding(b),==,1);goodix_fpi_usb_backend_complete_receive(b,11,frame,sizeof frame,NULL);g_assert_cmpuint(goodix_fpi_usb_backend_get_delivery_count(b),==,1);g_assert_cmpuint(goodix_fpi_usb_backend_get_max_outstanding(b),==,1);g_assert_true(goodix_fpi_usb_backend_can_free(b));goodix_fpi_usb_backend_free(b);goodix_usb_router_free(r);
}
static void test_async_out_cancel_drain(void){
  GoodixUsbRouter*r=goodix_usb_router_new(NULL,NULL,NULL);GoodixFpiUsbBackend*b=goodix_fpi_usb_backend_new(NULL,r,0x81,0x01,64);g_autoptr(GCancellable)c=g_cancellable_new();g_autoptr(GError)e=NULL;g_autoptr(GBytes)x=g_bytes_new_static("x",1);guint drained=0;
  goodix_fpi_usb_backend_set_async_submit_seam(b,async_noop,NULL);goodix_fpi_usb_backend_set_drained_callback(b,drained_count,&drained);goodix_usb_router_begin_generation(r,20);g_assert_true(goodix_fpi_usb_backend_begin_generation(b,20,c,&e));g_assert_true(goodix_fpi_usb_backend_submit_out(b,20,x,&e));g_assert_cmpuint(goodix_fpi_usb_backend_get_out_outstanding(b),==,1);goodix_fpi_usb_backend_cancel(b);g_assert_false(goodix_fpi_usb_backend_is_drained(b));g_assert_false(goodix_fpi_usb_backend_can_free(b));goodix_fpi_usb_backend_complete_out(b,20,NULL);g_assert_cmpuint(goodix_fpi_usb_backend_get_out_outstanding(b),==,0);g_assert_cmpuint(drained,==,1);g_assert_true(goodix_fpi_usb_backend_is_drained(b));g_assert_true(goodix_fpi_usb_backend_can_free(b));goodix_fpi_usb_backend_free(b);goodix_usb_router_free(r);
}
int main(int argc,char**argv){g_test_init(&argc,&argv,NULL);g_test_add_func("/goodix/d276-04/handshake-application-router",test_handshake_application_router);g_test_add_func("/goodix/d276-04/a0-stale-cancel-backend",test_a0_stale_cancel_backend);g_test_add_func("/goodix/d276-04/bad-credentials-terminal",test_bad_credentials_and_terminal);g_test_add_func("/goodix/d276-04/async-in-cancel-drain",test_async_in_cancel_drain);g_test_add_func("/goodix/d276-04/async-out-cancel-drain",test_async_out_cancel_drain);return g_test_run();}
